import './globals.css';
import Link from 'next/link';

// import localFont from 'next/font/local';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

export const metadata = {
  title: {
    default: 'Home | Poll App',
    template: '%s | Poll-App',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav className="main-nav">
            <div className="left-nav">
              <Link href="/">Home</Link>
            </div>
            <div className="right-nav">
              <Link href="/login">Sign In</Link>
              <details className="dropdown">
                <summary className="dropdown-summary">Menu</summary>
                <div className="dropdown-content">
                  <Link href="/register">Sign Up</Link>
                  <Link href="/polls">Polls</Link>
                  <Link href="/profile">Profile</Link>
                </div>
              </details>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}

/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */
